# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1390ce5faec91d45bae57e06148087457b78c8dbbe29bb89aff780ff20176c8e08c5e6fe86263febf4672faabbb16cccc310fabcefc6fa29314da7943ae13796

test:
  secret_key_base: ebac9eeff49f962780b41f0b1dbda6bb81c6c0a8111d35cdf99271b2e8d79ddbf18be49ca7ff1602e77819775644bbf07bd72bb4d8750b5450c3b35861b87bfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
